config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spots#index"
  resources :spots, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
  resources :comments, only: :create
end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot

  validates :content, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '漫画' },
    { id: 3, name: 'アニメ' },
    { id: 4, name: '人物' },
    { id: 5, name: '映画' },
    { id: 6, name: 'ドラマ' },
    { id: 7, name: '音楽' },
    { id: 8, name: '文学' },
    { id: 9, name: 'ゲーム' },
    { id: 10, name: '歴史' }
  ]
 
   include ActiveHash::Associations
   has_many :spots
 
  end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :users
  has_many :spots
  end

app/models/spot.rb
class Spot < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :prefecture
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :city, presence: true

  validates :prefecture_id, numericality: {other_than: 1, message: "can't be blank"}
  validates :genre_id, numericality: {other_than: 1, message: "can't be blank"}
  
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  has_many :spots
  has_many :comments, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # パスワードは、半角英数字混合での入力が必須であること
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  validates :nickname, presence: true
  validates :birth_date, presence: true

  # お名前(全角)は、全角（漢字・ひらがな・カタカナ）での入力が必須であること
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力してください' }
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力してください' }
  
  # お名前カナ(全角)は、全角（カタカナ）での入力が必須であること。
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}ー－&&[^ -~｡-ﾟ]]+\z/, message: 'は全角カタカナで入力してください' }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}ー－&&[^ -~｡-ﾟ]]+\z/, message: 'は全角カタカナで入力してください' }

  validates :prefecture_id, numericality: {other_than: 1, message: "can't be blank"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_date, :last_name, :first_name, :last_name_kana, :first_name_kana, :prefecture_id])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to spot_path(@comment.spot)

    else
      @spot = Spot.find(@comment.spot_id)
      @comments = @spot.comments
      render "spots/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, spot_id: params[:spot_id])
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    if params[:genre_id].to_i > 1
     @spots = Spot.where(genre_id: params[:genre_id]).order("created_at DESC")
    
    else
     @spots = Spot.includes(:user).order("created_at DESC")
    end
  end

  def new
    @spot = Spot.new
  end
  
  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @spot.comments
  end

  def edit
  end

  def update
    if @spot.update(spot_params)
      redirect_to spot_path(@spot)
    else
      render :edit
    end
  end

  def destroy
    if @spot.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end


private

  def spot_params
    params.require(:spot).permit(:genre_id, :title, :catch_copy, :postal_code, :prefecture_id, :city, :addresses, :image).merge(user_id: current_user.id)
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @spot.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>聖地Navi</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
    <div class="inner">
     <div class="nav">
     
        <h1 class="logo"><a href="/">📍聖地Navi</a></h1>

     <% if user_signed_in? %>
      <div class="greeting">
       <%= "こんにちは、#{current_user.nickname}さん" %><br>マイページは
       <%= link_to "こちら", user_path(current_user), class: :greeting__link%>です！
      </div>
     <% end %>

        <% if user_signed_in? %>
          <div class="nav__right">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__btn" %>
            <%= link_to "新規投稿", new_spot_path, class: "nav__btn" %>
          </div>
        <% else %>
          <div class="nav__right">
            <%= link_to "ログイン",  new_user_session_path, class: "nav__btn" %>
            <%= link_to "新規登録", new_user_registration_path, class: "nav__btn" %>
          </div>
        <% end %>
      </div>
     </div>
    </header>

     <% if current_page?(root_path) %>
      <ul class="lists">
         <%= link_to "すべて", root_path(genre_id:0), class:"genre_tag1"%>
         <%= link_to "漫画", root_path(genre_id:2), class:"genre_tag2"%>
         <%= link_to "アニメ", root_path(genre_id:3), class:"genre_tag3"%>
         <%= link_to "人物", root_path(genre_id:4), class:"genre_tag4"%>
         <%= link_to "映画", root_path(genre_id:5), class:"genre_tag5"%>
         <%= link_to "ドラマ", root_path(genre_id:6), class:"genre_tag6"%>
         <%= link_to "音楽", root_path(genre_id:7), class:"genre_tag7"%>
         <%= link_to "文学", root_path(genre_id:8), class:"genre_tag8"%>
         <%= link_to "ゲーム", root_path(genre_id:9), class:"genre_tag9"%>
         <%= link_to "歴史", root_path(genre_id:10), class:"genre_tag10"%>
      </ul>
     <% else %>
     <% end %>

    <%= yield %>

    <footer class="footer">
      <p class="copyright">Copyright © 聖地Navi All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/spots/_form.html.erb
<div class="main">
<%= form_with model: @spot, local: true do |f|%>

<div class="form-group">
    <%= f.label :image, "聖地の画像", class:"form-text" %><span class="indispensable">必須</span><br />
    <%= f.file_field :image, id:"spot_image" %>
  </div>

<div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ジャンル<span class="indispensable">必須</span></label>
    </div>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %>
  </div>

  <div class="form-group">
    <%= f.label :title, "聖地が登場する作品名", class:"form-text" %><span class="indispensable">必須</span><br />
    <%= f.text_field :title, id:"spot_title" %>
  </div>

  <div class="form-group">
    <%= f.label :postal_code, "郵便番号", class:"form-text"%><br />
    <%= f.text_field :postal_code, id:"spot_postal_code" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">都道府県<span class="indispensable">必須</span></label>
    </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="form-group">
    <%= f.label :city, "市区町村", class:"form-text" %><span class="indispensable">必須</span><br />
    <%= f.text_field :city, id:"spot_city" %>
  </div>

   <div class="form-group">
    <%= f.label :addresses, "住所", class:"form-text" %><br />
    <%= f.text_field :addresses, id:"spot_addresses" %>
  </div>

<div class="form-group">
    <%= f.label :catch_copy, "投稿者のコメント", class:"form-text" %><span class="indispensable">必須</span><br />
    <%= f.text_field :catch_copy, id:"spot_catch_copy" %>
  </div>

 <div class="form-group">
  <div class="actions">
    <%= f.submit "投稿する",class:"color-btn" %>
  </div>
  </div>
<% end %>
</div>

app/views/spots/_spot.html.erb
<div class="container">
  <div class="user_card">

  <% if spot.genre.id == 2 %>
  <div class="genre_mark2" spot-genre-id="2">●&nbsp</div>
  <% elsif spot.genre.id == 3 %>
  <div class="genre_mark3" spot-genre-id="3">●&nbsp</div>
  <% elsif spot.genre.id == 4 %>
  <div class="genre_mark4" spot-genre-id="4">●&nbsp</div>
  <% elsif spot.genre.id == 5 %>
  <div class="genre_mark5" spot-genre-id="5">●&nbsp</div>
  <% elsif spot.genre.id == 6 %>
  <div class="genre_mark6" spot-genre-id="6">●&nbsp</div>
  <% elsif spot.genre.id == 7 %>
  <div class="genre_mark7" spot-genre-id="7">●&nbsp</div>
  <% elsif spot.genre.id == 8 %>
  <div class="genre_mark8" spot-genre-id="8">●&nbsp</div>
  <% elsif spot.genre.id == 9 %>
  <div class="genre_mark9" spot-genre-id="9">●&nbsp</div>
  <% elsif spot.genre.id == 10 %>
  <div class="genre_mark10" spot-genre-id="10">●&nbsp</div>
  <% else %>
  <% end %>


  <%= link_to "#{spot.user.nickname}の投稿", user_path(spot.user), class: :spot__user %>
  </div>

  <div class="image_card" ><%= link_to image_tag(spot.image, class: :card__img ), spot_path(spot) %></div>


  <div class="spot_card">
   <%= link_to "📍 #{spot.prefecture.name}", spot_path(spot), class: :card__prefecture %>
   <%= link_to spot.city,  spot_path(spot) %>
    <%= "（#{spot.genre.name}）"%>
   </div>
   <%# <div class="communication">♡</div> %>
</div>

app/views/spots/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">聖地投稿ページ</h2>
       <%= render partial: "form", locals: { spot: @spot} %>
    </div>
  </div>
</div>

app/views/spots/index.html.erb
<main class="main">
  <div class="inner">
  
    <div class="card__wrapper">
    <%= render partial: "spot", collection: @spots %>
    </div>
  </div>
</main>

app/views/spots/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">聖地投稿ページ</h2>
       <%= render partial: "form", locals: { spot: @spot} %>
    </div>
  </div>
</div>

app/views/spots/show.html.erb
<main class="main">
  <div class="inner">
    <div class="spot__wrapper">
      <h2 class="page-heading">
         <%= link_to "#{@spot.user.nickname}さんの投稿の詳細", user_path(@spot.user), class: :spot__user %>
      </h2>

<div class="container">
 <div class="image_card"><%= link_to image_tag(@spot.image, class: :card__img ), spot_path(@spot) %></div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @spot.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">ジャンル</th>
          <td class="detail-value"><%= @spot.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-item">作品名</th>
          <td class="detail-value"><%= @spot.title %></td>
        </tr>
        <tr>
          <th class="detail-item">郵便番号</th>
          <td class="detail-value"><%= @spot.postal_code %></td>
        </tr>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= @spot.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">市区町村</th>
          <td class="detail-value"><%= @spot.city %></td>
        </tr>
        <th class="detail-item">住所</th>
          <td class="detail-value"><%= @spot.addresses %></td>
        </tr>
        <tr>
          <th class="detail-item">コメント</th>
          <td class="detail-value"><%= @spot.catch_copy %></td>
        </tr>

        <tr>
           <th class="detail-item">地図</th>
           <td class="detail-value">
        <div id="map" style="height: 400px;"></div>
           </td>
        </tr>

      </tbody>
    </table>
</div>

      <% if current_user == @spot.user%>
        <div class="editer">
          <%= link_to "投稿を編集", edit_spot_path(@spot), class:"edit-btn" %>
          <%= link_to "投稿を削除", spot_path(@spot), method: :delete, class:"edit-btn" %>
        </div>
      <% end %>

     <div class="spot__comments">
  <% if user_signed_in? %>
    <%= form_with model: [@spot, @comment], local: true do |f| %>
      <div class="field">
        <%= f.label :content, "コメント" %><br />
        <%= f.text_field :content, id: "comment_content" %>
      </div>
      <div class="actions">
        <%= f.submit "送信する", class: :form__btn %>
      </div>
    <% end %>
  <% end %>
       <ul class="comments_lists">
        <% @comments.each do |comment| %>
         <li class="comments_list">
           <%= comment.content %>
           <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
         </li>
       <% end %>
     </ul>
   </div>
  </div>
 </div>
</main>


<script>
  function initMap() {
    var city = '<%= @spot.city %>';
    var address = '<%= @spot.addresses %>';

    var fullAddress = city + ' ' + address;

    var geocoder = new google.maps.Geocoder();
    geocoder.geocode({ 'address': fullAddress }, function(results, status) {
      if (status === 'OK') {
        var latitude = results[0].geometry.location.lat();
        var longitude = results[0].geometry.location.lng();

        var mapOptions = {
          center: { lat: latitude, lng: longitude },
          zoom: 15
        };

        var map = new google.maps.Map(document.getElementById('map'), mapOptions);

        var marker = new google.maps.Marker({
          position: { lat: latitude, lng: longitude },
          map: map
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }
</script>

<%# <script async defer src=ENV["MAP_API_KEY"]></script> %>
<script async defer src="<%= ENV["MAP_API_KEY"] %>"></script>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">

      <table class="table">
        <tbody>
          <%# <tr> %>
            <%# <th class="table__col1">ニックネーム</th> %>
            <%# <td class="table__col2"><%= @user.nickname %></td>
          <%# </tr> %>
          <%# <tr>
            <th class="table__col1">出身地</th>
            <td class="table__col2"><%= @user.prefecture.name%></td>
          <%# </tr> %> 
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿一覧"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'spots/spot', collection: @user.spots %>
      </div>
    </div>
  </div>
</div>